### ISSUE TITLE
Remove and ignore node_modules

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#1]
It's generally considered best practice not to commit [node_modules](https://github.com/khawjaahmad/cypress-test-data-generator/tree/main/node_modules) and instead list the `node_modules` directory in a `.gitignore` file.

An example `.gitignore` for Cypress could be

```text
node_modules
cypress/downloads
cypress/screenshots
cypress/videos
.vscode
.DS_Store
```

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
This issue has been resolved.

   1. Removed all committed `node_modules` directories from the repository.
   2. Updated the `.gitignore` file to include the mentioned entries.

   Closing this issue. Thank you for bringing this to my attention!

   Closes #1
