### ISSUE TITLE
Configure consistent licensing

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#2]
The licensing should be made consistent.

https://github.com/khawjaahmad/cypress-test-data-generator/blob/main/README.md#license says

This project is licensed under the MIT License.

https://github.com/khawjaahmad/cypress-test-data-generator/blob/a30200dc63f7b166323355d8fe80592931f91608/package.json#L17 specifies ISC

According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository it's considered best practice to include a license file.

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
The licensing has been made consistent across the project.

   Actions taken:
   1. Created a separate LICENSE file in the root of the repository with the full text of the MIT License.
   2. Updated the package.json file to correctly specify "MIT" as the license.

   Thank you for bringing this to my attention!

   Closes #2
