### ISSUE TITLE
Add a repo link to package.json

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#4]
`package.json` is missing a link to the [repository](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository)

It should have a section

```json
  "repository": "github:khawjaahmad/cypress-test-data-generator"
```

So although the README says "Please feel free to submit a Pull Request.", users will not be able to find the repository from the npm registry in order to do this.

```text
$ npm repo cypress-test-data-generator
npm error no repository
```

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
This issue has been resolved.

   Actions taken:
   1. Added the "repository" field to package.json with the correct GitHub repository link.
   2. Verified that the npm repo command now correctly identifies the repository.

   The package.json file now includes:
   "repository": "github:khawjaahmad/cypress-test-data-generator"

   Thank you for bringing this to my attention!

   Closes #4
