### ISSUE TITLE
Add author

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#5]
`package.json` has a blank author field

https://github.com/khawjaahmad/cypress-test-data-generator/blob/a30200dc63f7b166323355d8fe80592931f91608/package.json#L16

This should either be removed or author information added.

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
This issue has been resolved.

   Actions taken:
   1. Added author information to the [package.json](https://github.com/khawjaahmad/cypress-test-data-generator/blob/main/package.json) file.
   2. Verified that the author field now contains the correct information.

   Thank you for bringing this to my attention!

   Closes #5
