### ISSUE TITLE
Fix link to example file

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#6]
The [README > Examples](https://github.com/khawjaahmad/cypress-test-data-generator/blob/main/README.md#examples) link to
https://github.com/khawjaahmad/cypress-test-data-generator/blob/main/cypress/e2e/plugin-tests.cy.js points to a non-existent file.

This should be corrected to point to an existing example file.

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
This issue has been resolved. The link to the example file in the README has been corrected.

   Actions taken:
   1. Updated the [README.md](https://github.com/khawjaahmad/cypress-test-data-generator/blob/main/README.md) file to point to the correct example folder.
   2. Verified that the new link leads to an existing and relevant example folder.


   Thank you for bringing this to my attention!

   Closes #6
