### ISSUE TITLE
Remove spurious npm dist-tag entries

### ISSUE THREAD

**Issue by MikeMcC399** [khawjaahmad/cypress-test-data-generator#7]
The published npm package has many unexplained `dist-tag` entries:

```text
$ npm dist-tag ls cypress-test-data-generator
JavaScript: 1.0.0
alpha: 1.0.0
beta: 1.0.0
cypress: 1.0.0
data-generation: 1.0.0
latest: 1.0.0
npm: 1.0.0
open-source: 1.0.0
plugin: 1.0.0
test-automation: 1.0.0
testing: 1.0.0
utility: 1.0.0
```

Typically only `latest` is used and the remainder can probably be deleted.

## Related

- https://github.com/cypress-io/cypress-documentation/pull/5938

**Comment by khawjaahmad** [comment]
This issue has been resolved. Now, only the 'latest' tag remains, as recommended.

   Actions taken:
   1. Removed all dist-tags except 'latest' from the npm package.
   2. Verified that only the 'latest' tag is present using `npm dist-tag ls cypress-test-data-generator`.
   
Thank you for bringing this to my attention!

   Closes #7
